spring:
  application:
    name: carhop

  datasource:
    url: jdbc:postgresql://localhost:5432/carhop
    username: postgres
    password: Archana@@@1

  jpa:
    hibernate:
      ddl-auto: update
    # Uncomment the following line if you want to enable SQL logging
    # show-sql: true
#jwt:
#  secret: dXNlLXNhZmUtYmFzZTY0LWVuY29kaW5n
#  expiration: 36000000

  jwt:
    secret: "${JWT_SECRET}"
    expiration: "${JWT_EXPIRATION:3600000}"