spring:
  application:
    name: carhop

  datasource:
    url: jdbc:postgresql://localhost:5432/carhop
    username: postgres
    password: Archana@@@1

  jpa:
    hibernate:
      ddl-auto: update
    # Uncomment the following line if you want to enable SQL logging
    # show-sql: true
